### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [musamairshad/Expense-Tracker-App#2]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/musamairshad-Expense-Tracker-App

**Comment by musamairshad** [comment]
I just checked the web app and found some issues related to adding or deleting the expenses.

**Comment by musamairshad** [comment]
I just checked the web app and found some issues related to adding or deleting the expenses.
